// <auto-generated />
using System;
using ContentDAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContentDAL.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    partial class ContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContentDomain.Entity.CollaborationSnapshot", b =>
                {
                    b.Property<int>("CollaborationSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("collaborationsnapshotid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CollaborationSnapshotId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatarurl");

                    b.Property<int>("CollaborationId")
                        .HasColumnType("integer")
                        .HasColumnName("collaborationid");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("externalid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("syncedat")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CollaborationSnapshotId")
                        .HasName("pk_collaborationsnapshots");

                    b.HasIndex("CollaborationId")
                        .IsUnique()
                        .HasDatabaseName("ix_collaborationsnapshots_collaborationid");

                    b.ToTable("collaborationsnapshots");
                });

            modelBuilder.Entity("ContentDomain.Entity.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("commentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("createdby");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted")
                        .HasDefaultValueSql("false");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentcommentid");

                    b.Property<int>("PostAuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("postauthorid");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("postid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updatedby");

                    b.HasKey("CommentId")
                        .HasName("pk_comments");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_comments_parentcommentid");

                    b.HasIndex("PostAuthorId")
                        .HasDatabaseName("ix_comments_postauthorid");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_comments_postid");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("ContentDomain.Entity.Like", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("likeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LikeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("postid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("LikeId")
                        .HasName("pk_likes");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_likes_postid_userid");

                    b.ToTable("likes");
                });

            modelBuilder.Entity("ContentDomain.Entity.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("postid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostId"));

                    b.Property<int?>("CollaborationSnapshotId")
                        .HasColumnType("integer")
                        .HasColumnName("collaborationsnapshotid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("createdby");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("externallink");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("isdeleted")
                        .HasDefaultValueSql("false");

                    b.Property<int?>("PostAuthorId")
                        .HasColumnType("integer")
                        .HasColumnName("postauthorid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Published'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updatedby");

                    b.HasKey("PostId")
                        .HasName("pk_posts");

                    b.HasIndex("CollaborationSnapshotId")
                        .HasDatabaseName("ix_posts_collaborationsnapshotid");

                    b.HasIndex("PostAuthorId")
                        .HasDatabaseName("ix_posts_postauthorid");

                    b.ToTable("posts", t =>
                        {
                            t.HasCheckConstraint("ck_post_authororcollaboration", "(postauthorid IS NOT NULL AND collaborationsnapshotid IS NULL) OR (postauthorid IS NULL AND collaborationsnapshotid IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ContentDomain.Entity.PostAuthor", b =>
                {
                    b.Property<int>("PostAuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("postauthorid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostAuthorId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatarurl");

                    b.Property<DateTime>("SyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("syncedat")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("PostAuthorId")
                        .HasName("pk_postauthors");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_postauthors_userid");

                    b.ToTable("postauthors");
                });

            modelBuilder.Entity("ContentDomain.Entity.PostMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bucket");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contenttype");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("objectname");

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("postid");

                    b.HasKey("Id")
                        .HasName("pk_postmedia");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_postmedia_postid");

                    b.ToTable("postmedia");
                });

            modelBuilder.Entity("ContentDomain.Entity.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("postid");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tagid");

                    b.HasKey("PostId", "TagId")
                        .HasName("pk_posttags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_posttags_tagid");

                    b.ToTable("posttags");
                });

            modelBuilder.Entity("ContentDomain.Entity.PostView", b =>
                {
                    b.Property<int>("PostViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("postviewid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostViewId"));

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("postid");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<DateTime>("ViewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewedat")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PostViewId")
                        .HasName("pk_postviews");

                    b.HasIndex("PostId")
                        .HasDatabaseName("ix_postviews_postid");

                    b.ToTable("postviews");
                });

            modelBuilder.Entity("ContentDomain.Entity.SavedPost", b =>
                {
                    b.Property<int>("SavedPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("savedpostid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SavedPostId"));

                    b.Property<int>("PostId")
                        .HasColumnType("integer")
                        .HasColumnName("postid");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("savedat")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("SavedPostId")
                        .HasName("pk_savedposts");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_savedposts_postid_userid");

                    b.ToTable("savedposts");
                });

            modelBuilder.Entity("ContentDomain.Entity.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tagid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("TagId")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("ContentDomain.Entity.Comment", b =>
                {
                    b.HasOne("ContentDomain.Entity.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_comments_parentcommentid");

                    b.HasOne("ContentDomain.Entity.PostAuthor", "Author")
                        .WithMany()
                        .HasForeignKey("PostAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_postauthors_postauthorid");

                    b.HasOne("ContentDomain.Entity.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_posts_postid");

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ContentDomain.Entity.Like", b =>
                {
                    b.HasOne("ContentDomain.Entity.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_likes_posts_postid");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ContentDomain.Entity.Post", b =>
                {
                    b.HasOne("ContentDomain.Entity.CollaborationSnapshot", "Collaboration")
                        .WithMany("Posts")
                        .HasForeignKey("CollaborationSnapshotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_posts_collaborationsnapshots_collaborationsnapshotid");

                    b.HasOne("ContentDomain.Entity.PostAuthor", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("PostAuthorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_posts_postauthors_postauthorid");

                    b.Navigation("Author");

                    b.Navigation("Collaboration");
                });

            modelBuilder.Entity("ContentDomain.Entity.PostMedia", b =>
                {
                    b.HasOne("ContentDomain.Entity.Post", "Post")
                        .WithMany("Media")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_postmedia_posts_postid");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ContentDomain.Entity.PostTag", b =>
                {
                    b.HasOne("ContentDomain.Entity.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posttags_posts_postid");

                    b.HasOne("ContentDomain.Entity.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posttags_tags_tagid");

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ContentDomain.Entity.PostView", b =>
                {
                    b.HasOne("ContentDomain.Entity.Post", "Post")
                        .WithMany("Views")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_postviews_posts_postid");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ContentDomain.Entity.SavedPost", b =>
                {
                    b.HasOne("ContentDomain.Entity.Post", "Post")
                        .WithMany("SavedPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_savedposts_posts_postid");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ContentDomain.Entity.CollaborationSnapshot", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ContentDomain.Entity.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ContentDomain.Entity.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Media");

                    b.Navigation("PostTags");

                    b.Navigation("SavedPosts");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("ContentDomain.Entity.PostAuthor", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ContentDomain.Entity.Tag", b =>
                {
                    b.Navigation("PostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
